"""
Pydantic models used in the Deep Research SDK.
"""

from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional, Set, Union

from pydantic import BaseModel, Field, HttpUrl


class ActivityStatus(str, Enum):
    """Status of a research activity."""

    PENDING = "pending"
    COMPLETE = "complete"
    ERROR = "error"


class ActivityType(str, Enum):
    """Type of research activity."""

    SEARCH = "search"
    EXTRACT = "extract"
    ANALYZE = "analyze"
    REASONING = "reasoning"
    SYNTHESIS = "synthesis"
    THOUGHT = "thought"


class ResearchPhase(str, Enum):
    """Current phase of the research process."""

    INITIALIZATION = "initialization"
    EXPLORATION = "exploration"
    DEEPENING = "deepening"
    VERIFICATION = "verification"
    SYNTHESIS = "synthesis"


class ResearchStrategy(str, Enum):
    """Strategy for conducting research."""

    BREADTH_FIRST = "breadth_first"
    DEPTH_FIRST = "depth_first"
    VERIFICATION = "verification"
    GAP_FILLING = "gap_filling"


class ActivityItem(BaseModel):
    """A single activity item in the research process."""

    type: ActivityType
    status: ActivityStatus
    message: str
    timestamp: datetime = Field(default_factory=datetime.now)
    depth: Optional[int] = None


class SourceItem(BaseModel):
    """A source of information used in the research."""

    url: HttpUrl | str
    title: str
    relevance: float = Field(ge=0.0, le=1.0)
    description: Optional[str] = None


class WebSearchItem(BaseModel):
    """A standard format for search results from any provider."""

    url: HttpUrl | str
    title: str
    description: str = ""
    relevance: float = Field(default=1.0, ge=0.0, le=1.0)
    provider: str = "unknown"  # This should match a value from WebSearchProvider enum
    date: str = ""


class SearchResult(BaseModel):
    """Result from a search operation."""

    success: bool
    data: Optional[List[WebSearchItem]] = None
    error: Optional[str] = None


class ExtractResult(BaseModel):
    """Result from an extraction operation."""

    success: bool
    data: Optional[Union[str, List[Dict]]] = None
    error: Optional[str] = None


class SearchQuery(BaseModel):
    """A search query generated by the reasoning model."""

    query: str
    relevance: float = Field(default=1.0, ge=0.0, le=1.0)
    explanation: Optional[str] = None
    phase: Optional[str] = None  # Which research phase generated this query


class ResearchResult(BaseModel):
    """Final result of the research process."""

    success: bool
    data: Optional[Dict] = None
    error: Optional[str] = None


class SourceQualityMetrics(BaseModel):
    """Quality metrics for a source."""

    domain_authority: float = Field(default=0.5, ge=0.0, le=1.0)
    recency_score: float = Field(default=0.5, ge=0.0, le=1.0)
    content_depth: float = Field(default=0.5, ge=0.0, le=1.0)
    citation_count: int = Field(default=0, ge=0)
    cross_reference_score: float = Field(default=0.0, ge=0.0, le=1.0)

    def composite_score(self) -> float:
        """Calculate composite quality score."""
        return (
            self.domain_authority * 0.3
            + self.recency_score * 0.2
            + self.content_depth * 0.3
            + self.cross_reference_score * 0.2
        )


class ConfirmedFact(BaseModel):
    """A fact confirmed by multiple sources."""

    claim: str
    confidence: float = Field(ge=0.0, le=1.0)
    sources: List[str] = Field(default_factory=list)
    supporting_evidence: List[str] = Field(default_factory=list)


class UnconfirmedClaim(BaseModel):
    """A claim that needs verification."""

    claim: str
    source: str
    needs_verification: bool = True
    contradictions: List[str] = Field(default_factory=list)


class Contradiction(BaseModel):
    """Conflicting information from different sources."""

    topic: str
    claim_a: str
    source_a: str
    claim_b: str
    source_b: str
    resolved: bool = False


class EnhancedResearchState(BaseModel):
    """Enhanced state tracking for the research process."""

    # Basic tracking
    current_phase: ResearchPhase = ResearchPhase.INITIALIZATION
    current_depth: int = 0
    completed_steps: int = 0
    total_expected_steps: int = 0
    failed_attempts: int = 0
    max_failed_attempts: int = 3

    # Research goals and findings
    research_goals: List[str] = Field(default_factory=list)
    findings: List[Dict[str, str]] = Field(default_factory=list)
    summaries: List[str] = Field(default_factory=list)

    # Knowledge organization
    confirmed_facts: List[ConfirmedFact] = Field(default_factory=list)
    unconfirmed_claims: List[UnconfirmedClaim] = Field(default_factory=list)
    contradictions: List[Contradiction] = Field(default_factory=list)

    # Source tracking
    sources: List[SourceItem] = Field(default_factory=list)
    visited_urls: Set[str] = Field(default_factory=set)
    source_quality_map: Dict[str, SourceQualityMetrics] = Field(default_factory=dict)

    # Query management
    search_queries: List[SearchQuery] = Field(default_factory=list)
    next_search_topic: str = ""
    url_to_search: str = ""

    # Knowledge gaps
    priority_gaps: List[str] = Field(default_factory=list)

    # Novelty tracking (for diminishing returns detection)
    recent_findings_count: List[int] = Field(default_factory=list)

    class Config:
        """Pydantic config."""

        arbitrary_types_allowed = True
