name: PyPy Release
on:
  release:
    types: [published, edited]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install pip and poetry
      run: |
        python -m pip install --upgrade pip
        python -m pip install uv==0.6.12
        ls -la
        uv sync

    - name: Publish to PyPI
      run: |
        uv build
        uv publish
